import type { Metadata } from "next";
import { Oswald, Roboto } from "next/font/google";
import "./globals.css";
//import Header from "./Components/Header";
import Footer from "./Components/Footer";
import Navbar from "./Components/Navbar";
import AppContextProvider from "./context/AppContext";



const roboto = Roboto({
  weight: ['200','300','400','500','600','700'],
  variable: "--font-oswald",
  subsets: ["latin"],
});

const oswald = Oswald({
  weight: ['200','300','400','500','600','700'],
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Uhayele",
  description: "Generated by Cp Development",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth ">
     
       <body  className={`${oswald.variable} ${roboto.variable}  w-full max-w-[1920px] mx-auto  bg-white `}>
     
        <AppContextProvider>
            <Navbar />
         <main className="relative overflow-hidden">
        {children}
         </main> 
         <Footer/>  
        </AppContextProvider>
     
       </body>
   
    </html>
  );
}
