import type { Metadata } from "next";
import {
  ClerkProvider,
} from '@clerk/nextjs'
import { dark } from '@clerk/themes'
import { Oswald, Roboto } from "next/font/google";
import "./globals.css";
//import Header from "./Components/Header";
import Footer from "./Components/Footer";
import Navbar from "./Components/Navbar";
import AppContextProvider from "./context/AppContext";
import { ThemeProvider } from "next-themes";




const roboto = Roboto({
  weight: ['200','300','400','500','600','700'],
  variable: "--font-oswald",
  subsets: ["latin"],
});

const oswald = Oswald({
  weight: ['200','300','400','500','600','700'],
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Uhayele",
  description: "Generated by Cp Development",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth " suppressHydrationWarning>
     
       <body  className={`${oswald.variable} ${roboto.variable} antialised   `}>
        <ClerkProvider  
         appearance={{
        baseTheme: dark,
      }}
      >
        <AppContextProvider>
              <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
     
   <Navbar />
         <main className="relative overflow-hidden">
        {children}
         </main> 
         <Footer/>  
         
          </ThemeProvider>
         
        </AppContextProvider>
     </ClerkProvider>
       </body>
   
    </html>
  );
}
